// apps/backend/src/modules/informes/informes-predefinidos.ts
// Informes predefinidos que se inicializan automáticamente al crear una empresa

import {
  ModuloInforme,
  TipoInforme,
  TipoCampo,
  TipoAgregacion,
  OperadorFiltro,
  TipoGraficoInforme,
  IInforme,
} from './Informe';

/**
 * Obtiene los informes predefinidos
 * No incluye empresaId porque cada empresa tiene su propia BD
 * @returns Array de informes predefinidos
 */
export function obtenerInformesPredefinidos(): Partial<IInforme>[] {
  return [
    // ============================================
    // VENTAS
    // ============================================
    {
      nombre: 'Listado de Facturas',
      descripcion: 'Listado completo de facturas emitidas con filtros',
      modulo: ModuloInforme.VENTAS,
      tipo: TipoInforme.TABLA,
      icono: 'FileText',
      fuente: { coleccion: 'facturas' },
      campos: [
        { campo: 'codigo', etiqueta: 'Número', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'fecha', etiqueta: 'Fecha', tipo: TipoCampo.FECHA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 2 },
        { campo: 'clienteNombre', etiqueta: 'Cliente', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 3 },
        { campo: 'clienteNif', etiqueta: 'NIF', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 4 },
        { campo: 'totales.subtotalNeto', etiqueta: 'Base', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 5 },
        { campo: 'totales.totalIva', etiqueta: 'IVA', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 6 },
        { campo: 'totales.totalFactura', etiqueta: 'Total', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 7 },
        { campo: 'estado', etiqueta: 'Estado', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 8 },
      ],
      filtros: [],
      parametros: [
        { nombre: 'fechaDesde', etiqueta: 'Desde', tipo: 'fecha', requerido: false },
        { nombre: 'fechaHasta', etiqueta: 'Hasta', tipo: 'fecha', requerido: false },
        { nombre: 'estado', etiqueta: 'Estado', tipo: 'select', requerido: false, opciones: [
          { valor: '', etiqueta: 'Todos' },
          { valor: 'borrador', etiqueta: 'Borrador' },
          { valor: 'pendiente_cobro', etiqueta: 'Pendiente cobro' },
          { valor: 'parcialmente_cobrada', etiqueta: 'Parcialmente cobrada' },
          { valor: 'cobrada', etiqueta: 'Cobrada' },
          { valor: 'vencida', etiqueta: 'Vencida' },
          { valor: 'anulada', etiqueta: 'Anulada' },
        ]},
        { nombre: 'serie', etiqueta: 'Serie', tipo: 'texto', requerido: false },
      ],
      agrupaciones: [],
      ordenamiento: [{ campo: 'fecha', direccion: 'desc' }],
      config: { paginacion: true, mostrarTotales: true, exportable: true, formatos: ['excel', 'pdf', 'csv'] },
      esPlantilla: true,
      compartido: true,
      orden: 1,
    },
    {
      nombre: 'Facturas Pendientes de Cobro',
      descripcion: 'Facturas emitidas pendientes de cobrar',
      modulo: ModuloInforme.VENTAS,
      tipo: TipoInforme.TABLA,
      icono: 'Receipt',
      fuente: { coleccion: 'facturas' },
      campos: [
        { campo: 'codigo', etiqueta: 'Número', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'fecha', etiqueta: 'Fecha', tipo: TipoCampo.FECHA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 2 },
        { campo: 'fechaVencimiento', etiqueta: 'Vencimiento', tipo: TipoCampo.FECHA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 3 },
        { campo: 'clienteNombre', etiqueta: 'Cliente', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 4 },
        { campo: 'totales.totalFactura', etiqueta: 'Total', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 5 },
        { campo: 'importeCobrado', etiqueta: 'Cobrado', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 6 },
        { campo: 'importePendiente', etiqueta: 'Pendiente', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 7 },
        { campo: 'estado', etiqueta: 'Estado', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 8 },
      ],
      filtros: [
        { campo: 'importePendiente', operador: OperadorFiltro.MAYOR, valor: 0 },
      ],
      parametros: [
        { nombre: 'fechaDesde', etiqueta: 'Desde', tipo: 'fecha', requerido: false },
        { nombre: 'fechaHasta', etiqueta: 'Hasta', tipo: 'fecha', requerido: false },
      ],
      agrupaciones: [],
      ordenamiento: [{ campo: 'fecha', direccion: 'asc' }],
      config: { paginacion: true, mostrarTotales: true, exportable: true, formatos: ['excel', 'pdf'] },
      esPlantilla: true,
      compartido: true,
      orden: 2,
    },
    {
      nombre: 'Top Productos Vendidos',
      descripcion: 'Ranking de productos por ventas totales (basado en facturas)',
      modulo: ModuloInforme.VENTAS,
      tipo: TipoInforme.TABLA,
      icono: 'Package',
      fuente: { coleccion: 'facturas', unwindArray: 'lineas' },
      campos: [
        { campo: 'lineas.codigo', etiqueta: 'SKU', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'lineas.nombre', etiqueta: 'Producto', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 2 },
        { campo: 'lineas.cantidad', etiqueta: 'Uds. Vendidas', tipo: TipoCampo.NUMERO, visible: true, agregacion: TipoAgregacion.SUMA, orden: 3 },
        { campo: 'lineas.subtotal', etiqueta: 'Total Ventas', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 4 },
        { campo: 'lineas.margenTotalLinea', etiqueta: 'Margen', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 5 },
      ],
      filtros: [
        { campo: 'activo', operador: OperadorFiltro.IGUAL, valor: true },
        { campo: 'lineas.tipo', operador: OperadorFiltro.IGUAL, valor: 'producto' },
      ],
      parametros: [
        { nombre: 'fechaDesde', etiqueta: 'Desde', tipo: 'fecha', requerido: false },
        { nombre: 'fechaHasta', etiqueta: 'Hasta', tipo: 'fecha', requerido: false },
      ],
      agrupaciones: [{ campo: 'lineas.nombre', orden: 'desc' }],
      ordenamiento: [{ campo: 'lineas.subtotal', direccion: 'desc' }],
      config: { limite: 50, paginacion: true, mostrarTotales: true, exportable: true, formatos: ['excel', 'pdf'] },
      esPlantilla: true,
      compartido: true,
      orden: 3,
    },
    {
      nombre: 'Ventas por Cliente',
      descripcion: 'Resumen de facturación por cliente',
      modulo: ModuloInforme.VENTAS,
      tipo: TipoInforme.TABLA,
      icono: 'Users',
      fuente: { coleccion: 'facturas' },
      campos: [
        { campo: 'clienteNombre', etiqueta: 'Cliente', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'clienteNif', etiqueta: 'NIF', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 2 },
        { campo: 'totales.subtotalNeto', etiqueta: 'Base Imponible', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 3 },
        { campo: 'totales.totalIva', etiqueta: 'IVA', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 4 },
        { campo: 'totales.totalFactura', etiqueta: 'Total', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 5 },
        { campo: 'totales.margenBruto', etiqueta: 'Margen', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 6 },
      ],
      filtros: [
        { campo: 'activo', operador: OperadorFiltro.IGUAL, valor: true },
      ],
      parametros: [
        { nombre: 'fechaDesde', etiqueta: 'Desde', tipo: 'fecha', requerido: false },
        { nombre: 'fechaHasta', etiqueta: 'Hasta', tipo: 'fecha', requerido: false },
        { nombre: 'estado', etiqueta: 'Estado', tipo: 'select', requerido: false, opciones: [
          { valor: '', etiqueta: 'Todos' },
          { valor: 'cobrada', etiqueta: 'Cobrada' },
          { valor: 'pendiente_cobro', etiqueta: 'Pendiente cobro' },
          { valor: 'parcialmente_cobrada', etiqueta: 'Parcialmente cobrada' },
        ]},
        { nombre: 'serie', etiqueta: 'Serie', tipo: 'texto', requerido: false },
      ],
      agrupaciones: [{ campo: 'clienteNombre', orden: 'asc' }],
      ordenamiento: [{ campo: 'totales.totalFactura', direccion: 'desc' }],
      config: { paginacion: true, mostrarTotales: true, exportable: true, formatos: ['excel', 'pdf'] },
      esPlantilla: true,
      compartido: true,
      orden: 4,
    },
    {
      nombre: 'Resumen de Márgenes',
      descripcion: 'Análisis de márgenes por factura',
      modulo: ModuloInforme.VENTAS,
      tipo: TipoInforme.TABLA,
      icono: 'TrendingUp',
      fuente: { coleccion: 'facturas' },
      campos: [
        { campo: 'codigo', etiqueta: 'Factura', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'fecha', etiqueta: 'Fecha', tipo: TipoCampo.FECHA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 2 },
        { campo: 'clienteNombre', etiqueta: 'Cliente', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 3 },
        { campo: 'totales.totalFactura', etiqueta: 'Venta', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 4 },
        { campo: 'totales.costeTotal', etiqueta: 'Coste', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 5 },
        { campo: 'totales.margenBruto', etiqueta: 'Margen €', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 6 },
        { campo: 'totales.margenPorcentaje', etiqueta: 'Margen %', tipo: TipoCampo.PORCENTAJE, visible: true, agregacion: TipoAgregacion.PROMEDIO, orden: 7 },
      ],
      filtros: [
        { campo: 'activo', operador: OperadorFiltro.IGUAL, valor: true },
      ],
      parametros: [
        { nombre: 'fechaDesde', etiqueta: 'Desde', tipo: 'fecha', requerido: false },
        { nombre: 'fechaHasta', etiqueta: 'Hasta', tipo: 'fecha', requerido: false },
      ],
      agrupaciones: [],
      ordenamiento: [{ campo: 'fecha', direccion: 'desc' }],
      config: { paginacion: true, mostrarTotales: true, exportable: true, formatos: ['excel', 'pdf'] },
      esPlantilla: true,
      compartido: true,
      orden: 5,
    },
    {
      nombre: 'Listado de Ventas',
      descripcion: 'Detalle de facturas con totales para análisis de evolución',
      modulo: ModuloInforme.VENTAS,
      tipo: TipoInforme.TABLA,
      icono: 'BarChart',
      fuente: { coleccion: 'facturas' },
      campos: [
        { campo: 'codigo', etiqueta: 'Factura', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'fecha', etiqueta: 'Fecha', tipo: TipoCampo.FECHA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 2 },
        { campo: 'serie', etiqueta: 'Serie', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 3 },
        { campo: 'clienteNombre', etiqueta: 'Cliente', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 4 },
        { campo: 'totales.subtotalNeto', etiqueta: 'Base', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 5 },
        { campo: 'totales.totalIva', etiqueta: 'IVA', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 6 },
        { campo: 'totales.totalFactura', etiqueta: 'Total', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 7 },
      ],
      filtros: [
        { campo: 'activo', operador: OperadorFiltro.IGUAL, valor: true },
      ],
      parametros: [
        { nombre: 'fechaDesde', etiqueta: 'Desde', tipo: 'fecha', requerido: true },
        { nombre: 'fechaHasta', etiqueta: 'Hasta', tipo: 'fecha', requerido: true },
      ],
      agrupaciones: [],
      ordenamiento: [{ campo: 'fecha', direccion: 'asc' }],
      config: { paginacion: true, mostrarTotales: true, exportable: true, formatos: ['excel', 'pdf', 'csv'] },
      esPlantilla: true,
      compartido: true,
      orden: 6,
    },

    // ============================================
    // COMPRAS
    // ============================================
    {
      nombre: 'Listado de Facturas de Compra',
      descripcion: 'Listado completo de facturas recibidas de proveedores',
      modulo: ModuloInforme.COMPRAS,
      tipo: TipoInforme.TABLA,
      icono: 'FileText',
      fuente: { coleccion: 'facturacompras' },
      campos: [
        { campo: 'codigo', etiqueta: 'Código', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'numeroFacturaProveedor', etiqueta: 'Nº Proveedor', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 2 },
        { campo: 'fecha', etiqueta: 'Fecha', tipo: TipoCampo.FECHA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 3 },
        { campo: 'proveedorNombre', etiqueta: 'Proveedor', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 4 },
        { campo: 'proveedorNif', etiqueta: 'NIF', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 5 },
        { campo: 'totales.subtotalNeto', etiqueta: 'Base', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 6 },
        { campo: 'totales.totalIva', etiqueta: 'IVA', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 7 },
        { campo: 'totales.totalFactura', etiqueta: 'Total', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 8 },
        { campo: 'estado', etiqueta: 'Estado', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 9 },
      ],
      filtros: [],
      parametros: [
        { nombre: 'fechaDesde', etiqueta: 'Desde', tipo: 'fecha', requerido: false },
        { nombre: 'fechaHasta', etiqueta: 'Hasta', tipo: 'fecha', requerido: false },
        { nombre: 'estado', etiqueta: 'Estado', tipo: 'select', requerido: false, opciones: [
          { valor: '', etiqueta: 'Todos' },
          { valor: 'borrador', etiqueta: 'Borrador' },
          { valor: 'pendiente_pago', etiqueta: 'Pendiente pago' },
          { valor: 'parcialmente_pagada', etiqueta: 'Parcialmente pagada' },
          { valor: 'pagada', etiqueta: 'Pagada' },
          { valor: 'vencida', etiqueta: 'Vencida' },
          { valor: 'anulada', etiqueta: 'Anulada' },
        ]},
        { nombre: 'proveedorNombre', etiqueta: 'Proveedor', tipo: 'texto', requerido: false },
      ],
      agrupaciones: [],
      ordenamiento: [{ campo: 'fecha', direccion: 'desc' }],
      config: { paginacion: true, mostrarTotales: true, exportable: true, formatos: ['excel', 'pdf', 'csv'] },
      esPlantilla: true,
      compartido: true,
      orden: 1,
    },
    {
      nombre: 'Facturas Pendientes de Pago',
      descripcion: 'Facturas de compra pendientes de pagar a proveedores',
      modulo: ModuloInforme.COMPRAS,
      tipo: TipoInforme.TABLA,
      icono: 'Receipt',
      fuente: { coleccion: 'facturacompras' },
      campos: [
        { campo: 'codigo', etiqueta: 'Código', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'numeroFacturaProveedor', etiqueta: 'Nº Proveedor', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 2 },
        { campo: 'fecha', etiqueta: 'Fecha', tipo: TipoCampo.FECHA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 3 },
        { campo: 'fechaVencimiento', etiqueta: 'Vencimiento', tipo: TipoCampo.FECHA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 4 },
        { campo: 'proveedorNombre', etiqueta: 'Proveedor', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 5 },
        { campo: 'totales.totalFactura', etiqueta: 'Total', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 6 },
        { campo: 'importePendiente', etiqueta: 'Pendiente', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 7 },
        { campo: 'estado', etiqueta: 'Estado', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 8 },
      ],
      filtros: [
        { campo: 'estado', operador: OperadorFiltro.EN, valor: ['pendiente_pago', 'parcialmente_pagada', 'vencida'] },
      ],
      parametros: [
        { nombre: 'fechaDesde', etiqueta: 'Desde', tipo: 'fecha', requerido: false },
        { nombre: 'fechaHasta', etiqueta: 'Hasta', tipo: 'fecha', requerido: false },
      ],
      agrupaciones: [],
      ordenamiento: [{ campo: 'fechaVencimiento', direccion: 'asc' }],
      config: { paginacion: true, mostrarTotales: true, exportable: true, formatos: ['excel', 'pdf'] },
      esPlantilla: true,
      compartido: true,
      orden: 2,
    },
    {
      nombre: 'Compras por Proveedor',
      descripcion: 'Resumen de compras por proveedor',
      modulo: ModuloInforme.COMPRAS,
      tipo: TipoInforme.TABLA,
      icono: 'Building2',
      fuente: { coleccion: 'facturacompras' },
      campos: [
        { campo: 'proveedorNombre', etiqueta: 'Proveedor', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'proveedorNif', etiqueta: 'NIF', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 2 },
        { campo: 'totales.subtotalNeto', etiqueta: 'Base Imponible', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 3 },
        { campo: 'totales.totalIva', etiqueta: 'IVA', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 4 },
        { campo: 'totales.totalFactura', etiqueta: 'Total', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 5 },
      ],
      filtros: [
        { campo: 'activo', operador: OperadorFiltro.IGUAL, valor: true },
      ],
      parametros: [
        { nombre: 'fechaDesde', etiqueta: 'Desde', tipo: 'fecha', requerido: false },
        { nombre: 'fechaHasta', etiqueta: 'Hasta', tipo: 'fecha', requerido: false },
        { nombre: 'estado', etiqueta: 'Estado', tipo: 'select', requerido: false, opciones: [
          { valor: '', etiqueta: 'Todos' },
          { valor: 'pagada', etiqueta: 'Pagada' },
          { valor: 'pendiente_pago', etiqueta: 'Pendiente pago' },
          { valor: 'parcialmente_pagada', etiqueta: 'Parcialmente pagada' },
        ]},
      ],
      agrupaciones: [{ campo: 'proveedorNombre', orden: 'asc' }],
      ordenamiento: [{ campo: 'totales.totalFactura', direccion: 'desc' }],
      config: { paginacion: true, mostrarTotales: true, exportable: true, formatos: ['excel', 'pdf'] },
      esPlantilla: true,
      compartido: true,
      orden: 3,
    },
    {
      nombre: 'Listado de Compras',
      descripcion: 'Detalle de facturas de compra para análisis de evolución',
      modulo: ModuloInforme.COMPRAS,
      tipo: TipoInforme.TABLA,
      icono: 'BarChart',
      fuente: { coleccion: 'facturacompras' },
      campos: [
        { campo: 'codigo', etiqueta: 'Código', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'numeroFacturaProveedor', etiqueta: 'Nº Proveedor', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 2 },
        { campo: 'fecha', etiqueta: 'Fecha', tipo: TipoCampo.FECHA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 3 },
        { campo: 'proveedorNombre', etiqueta: 'Proveedor', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 4 },
        { campo: 'totales.subtotalNeto', etiqueta: 'Base', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 5 },
        { campo: 'totales.totalIva', etiqueta: 'IVA', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 6 },
        { campo: 'totales.totalFactura', etiqueta: 'Total', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 7 },
      ],
      filtros: [
        { campo: 'activo', operador: OperadorFiltro.IGUAL, valor: true },
      ],
      parametros: [
        { nombre: 'fechaDesde', etiqueta: 'Desde', tipo: 'fecha', requerido: true },
        { nombre: 'fechaHasta', etiqueta: 'Hasta', tipo: 'fecha', requerido: true },
      ],
      agrupaciones: [],
      ordenamiento: [{ campo: 'fecha', direccion: 'asc' }],
      config: { paginacion: true, mostrarTotales: true, exportable: true, formatos: ['excel', 'pdf', 'csv'] },
      esPlantilla: true,
      compartido: true,
      orden: 4,
    },

    // ============================================
    // STOCK / ALMACÉN
    // ============================================
    {
      nombre: 'Inventario Completo',
      descripcion: 'Listado completo de productos con stock y precios',
      modulo: ModuloInforme.STOCK,
      tipo: TipoInforme.TABLA,
      icono: 'Package',
      fuente: { coleccion: 'productos' },
      campos: [
        { campo: 'sku', etiqueta: 'SKU', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'nombre', etiqueta: 'Producto', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 2 },
        { campo: 'familia', etiqueta: 'Familia', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 3 },
        { campo: 'stock.cantidad', etiqueta: 'Stock', tipo: TipoCampo.NUMERO, visible: true, agregacion: TipoAgregacion.SUMA, orden: 4 },
        { campo: 'stock.minimo', etiqueta: 'Mínimo', tipo: TipoCampo.NUMERO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 5 },
        { campo: 'precios.compra', etiqueta: 'P.Coste', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 6 },
        { campo: 'precios.venta', etiqueta: 'P.Venta', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 7 },
        { campo: 'precios.pvp', etiqueta: 'PVP', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 8 },
      ],
      filtros: [
        { campo: 'activo', operador: OperadorFiltro.IGUAL, valor: true },
      ],
      parametros: [],
      agrupaciones: [],
      ordenamiento: [{ campo: 'nombre', direccion: 'asc' }],
      config: { paginacion: true, mostrarTotales: true, exportable: true, formatos: ['excel', 'pdf', 'csv'] },
      esPlantilla: true,
      compartido: true,
      orden: 1,
    },
    {
      nombre: 'Productos Bajo Mínimo',
      descripcion: 'Productos con stock por debajo del mínimo establecido',
      modulo: ModuloInforme.STOCK,
      tipo: TipoInforme.TABLA,
      icono: 'AlertTriangle',
      fuente: { coleccion: 'productos' },
      campos: [
        { campo: 'sku', etiqueta: 'SKU', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'nombre', etiqueta: 'Producto', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 2 },
        { campo: 'familia', etiqueta: 'Familia', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 3 },
        { campo: 'stock.cantidad', etiqueta: 'Stock Actual', tipo: TipoCampo.NUMERO, visible: true, agregacion: TipoAgregacion.SUMA, orden: 4 },
        { campo: 'stock.minimo', etiqueta: 'Stock Mínimo', tipo: TipoCampo.NUMERO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 5 },
        { campo: 'precios.compra', etiqueta: 'P. Coste', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 6 },
      ],
      filtros: [
        { campo: 'activo', operador: OperadorFiltro.IGUAL, valor: true },
      ],
      parametros: [],
      agrupaciones: [],
      ordenamiento: [{ campo: 'stock.cantidad', direccion: 'asc' }],
      config: { paginacion: true, mostrarTotales: true, exportable: true, formatos: ['excel', 'pdf'] },
      esPlantilla: true,
      compartido: true,
      orden: 2,
    },
    {
      nombre: 'Productos Sin Movimiento',
      descripcion: 'Productos con stock que no han tenido ventas recientemente',
      modulo: ModuloInforme.STOCK,
      tipo: TipoInforme.TABLA,
      icono: 'PackageX',
      fuente: { coleccion: 'productos' },
      campos: [
        { campo: 'sku', etiqueta: 'SKU', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'nombre', etiqueta: 'Producto', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 2 },
        { campo: 'familia', etiqueta: 'Familia', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 3 },
        { campo: 'stock.cantidad', etiqueta: 'Stock', tipo: TipoCampo.NUMERO, visible: true, agregacion: TipoAgregacion.SUMA, orden: 4 },
        { campo: 'precios.compra', etiqueta: 'P. Coste', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 5 },
        { campo: 'estadisticas.ultimaVenta', etiqueta: 'Última Venta', tipo: TipoCampo.FECHA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 6 },
      ],
      filtros: [
        { campo: 'activo', operador: OperadorFiltro.IGUAL, valor: true },
        { campo: 'stock.cantidad', operador: OperadorFiltro.MAYOR, valor: 0 },
      ],
      parametros: [],
      agrupaciones: [],
      ordenamiento: [{ campo: 'estadisticas.ultimaVenta', direccion: 'asc' }],
      config: { paginacion: true, mostrarTotales: true, exportable: true, formatos: ['excel', 'pdf'] },
      esPlantilla: true,
      compartido: true,
      orden: 3,
    },

    // ============================================
    // CLIENTES
    // ============================================
    {
      nombre: 'Listado de Clientes',
      descripcion: 'Listado completo de clientes activos',
      modulo: ModuloInforme.CLIENTES,
      tipo: TipoInforme.TABLA,
      icono: 'Users',
      fuente: { coleccion: 'clientes' },
      campos: [
        { campo: 'codigo', etiqueta: 'Código', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'nombre', etiqueta: 'Nombre', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 2 },
        { campo: 'nif', etiqueta: 'NIF/CIF', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 3 },
        { campo: 'email', etiqueta: 'Email', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 4 },
        { campo: 'telefono', etiqueta: 'Teléfono', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 5 },
        { campo: 'tipoCliente', etiqueta: 'Tipo', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 6 },
        { campo: 'riesgoActual', etiqueta: 'Riesgo', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 7 },
      ],
      filtros: [
        { campo: 'activo', operador: OperadorFiltro.IGUAL, valor: true },
      ],
      parametros: [],
      agrupaciones: [],
      ordenamiento: [{ campo: 'nombre', direccion: 'asc' }],
      config: { paginacion: true, mostrarTotales: true, exportable: true, formatos: ['excel', 'pdf', 'csv'] },
      esPlantilla: true,
      compartido: true,
      orden: 1,
    },
    {
      nombre: 'Clientes con Saldo Pendiente',
      descripcion: 'Clientes con riesgo actual mayor que cero',
      modulo: ModuloInforme.CLIENTES,
      tipo: TipoInforme.TABLA,
      icono: 'AlertTriangle',
      fuente: { coleccion: 'clientes' },
      campos: [
        { campo: 'codigo', etiqueta: 'Código', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'nombre', etiqueta: 'Nombre', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 2 },
        { campo: 'nif', etiqueta: 'NIF/CIF', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 3 },
        { campo: 'telefono', etiqueta: 'Teléfono', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 4 },
        { campo: 'email', etiqueta: 'Email', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 5 },
        { campo: 'limiteCredito', etiqueta: 'Límite Crédito', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 6 },
        { campo: 'riesgoActual', etiqueta: 'Saldo Pendiente', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 7 },
      ],
      filtros: [
        { campo: 'activo', operador: OperadorFiltro.IGUAL, valor: true },
        { campo: 'riesgoActual', operador: OperadorFiltro.MAYOR, valor: 0 },
      ],
      parametros: [],
      agrupaciones: [],
      ordenamiento: [{ campo: 'riesgoActual', direccion: 'desc' }],
      config: { paginacion: true, mostrarTotales: true, exportable: true, formatos: ['excel', 'pdf'] },
      esPlantilla: true,
      compartido: true,
      orden: 2,
    },

    // ============================================
    // PROVEEDORES
    // ============================================
    {
      nombre: 'Listado de Proveedores',
      descripcion: 'Listado completo de proveedores activos',
      modulo: ModuloInforme.PROVEEDORES,
      tipo: TipoInforme.TABLA,
      icono: 'Building2',
      fuente: { coleccion: 'proveedores' },
      campos: [
        { campo: 'codigo', etiqueta: 'Código', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'nombre', etiqueta: 'Nombre', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 2 },
        { campo: 'nif', etiqueta: 'NIF/CIF', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 3 },
        { campo: 'email', etiqueta: 'Email', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 4 },
        { campo: 'telefono', etiqueta: 'Teléfono', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 5 },
        { campo: 'tipoProveedor', etiqueta: 'Tipo', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 6 },
      ],
      filtros: [
        { campo: 'activo', operador: OperadorFiltro.IGUAL, valor: true },
      ],
      parametros: [],
      agrupaciones: [],
      ordenamiento: [{ campo: 'nombre', direccion: 'asc' }],
      config: { paginacion: true, mostrarTotales: false, exportable: true, formatos: ['excel', 'pdf', 'csv'] },
      esPlantilla: true,
      compartido: true,
      orden: 1,
    },

    // ============================================
    // PRESUPUESTOS
    // ============================================
    {
      nombre: 'Listado de Presupuestos',
      descripcion: 'Listado completo de presupuestos con estado',
      modulo: ModuloInforme.PRESUPUESTOS,
      tipo: TipoInforme.TABLA,
      icono: 'FileText',
      fuente: { coleccion: 'presupuestos' },
      campos: [
        { campo: 'codigo', etiqueta: 'Número', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'fecha', etiqueta: 'Fecha', tipo: TipoCampo.FECHA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 2 },
        { campo: 'clienteNombre', etiqueta: 'Cliente', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 3 },
        { campo: 'titulo', etiqueta: 'Título', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 4 },
        { campo: 'totales.totalPresupuesto', etiqueta: 'Total', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 5 },
        { campo: 'estado', etiqueta: 'Estado', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 6 },
        { campo: 'fechaValidez', etiqueta: 'Válido Hasta', tipo: TipoCampo.FECHA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 7 },
      ],
      filtros: [],
      parametros: [
        { nombre: 'fechaDesde', etiqueta: 'Desde', tipo: 'fecha', requerido: false },
        { nombre: 'fechaHasta', etiqueta: 'Hasta', tipo: 'fecha', requerido: false },
      ],
      agrupaciones: [],
      ordenamiento: [{ campo: 'fecha', direccion: 'desc' }],
      config: { paginacion: true, mostrarTotales: true, exportable: true, formatos: ['excel', 'pdf'] },
      esPlantilla: true,
      compartido: true,
      orden: 1,
    },
    {
      nombre: 'Presupuestos Pendientes',
      descripcion: 'Presupuestos en estado pendiente de respuesta',
      modulo: ModuloInforme.PRESUPUESTOS,
      tipo: TipoInforme.TABLA,
      icono: 'Clock',
      fuente: { coleccion: 'presupuestos' },
      campos: [
        { campo: 'codigo', etiqueta: 'Número', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'fecha', etiqueta: 'Fecha', tipo: TipoCampo.FECHA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 2 },
        { campo: 'clienteNombre', etiqueta: 'Cliente', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 3 },
        { campo: 'titulo', etiqueta: 'Título', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 4 },
        { campo: 'totales.totalPresupuesto', etiqueta: 'Total', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 5 },
        { campo: 'fechaValidez', etiqueta: 'Válido Hasta', tipo: TipoCampo.FECHA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 6 },
      ],
      filtros: [
        { campo: 'estado', operador: OperadorFiltro.EN, valor: ['borrador', 'enviado', 'pendiente'] },
      ],
      parametros: [],
      agrupaciones: [],
      ordenamiento: [{ campo: 'fechaValidez', direccion: 'asc' }],
      config: { paginacion: true, mostrarTotales: true, exportable: true, formatos: ['excel', 'pdf'] },
      esPlantilla: true,
      compartido: true,
      orden: 2,
    },

    // ============================================
    // PEDIDOS
    // ============================================
    {
      nombre: 'Listado de Pedidos',
      descripcion: 'Listado completo de pedidos de venta',
      modulo: ModuloInforme.PEDIDOS,
      tipo: TipoInforme.TABLA,
      icono: 'ShoppingCart',
      fuente: { coleccion: 'pedidos' },
      campos: [
        { campo: 'codigo', etiqueta: 'Número', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'fecha', etiqueta: 'Fecha', tipo: TipoCampo.FECHA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 2 },
        { campo: 'clienteNombre', etiqueta: 'Cliente', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 3 },
        { campo: 'totales.totalPedido', etiqueta: 'Total', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 4 },
        { campo: 'estado', etiqueta: 'Estado', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 5 },
        { campo: 'prioridad', etiqueta: 'Prioridad', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 6 },
        { campo: 'fechaEntregaComprometida', etiqueta: 'Entrega', tipo: TipoCampo.FECHA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 7 },
      ],
      filtros: [],
      parametros: [
        { nombre: 'fechaDesde', etiqueta: 'Desde', tipo: 'fecha', requerido: false },
        { nombre: 'fechaHasta', etiqueta: 'Hasta', tipo: 'fecha', requerido: false },
      ],
      agrupaciones: [],
      ordenamiento: [{ campo: 'fecha', direccion: 'desc' }],
      config: { paginacion: true, mostrarTotales: true, exportable: true, formatos: ['excel', 'pdf'] },
      esPlantilla: true,
      compartido: true,
      orden: 1,
    },
    {
      nombre: 'Pedidos Pendientes',
      descripcion: 'Pedidos pendientes de servir o entregar',
      modulo: ModuloInforme.PEDIDOS,
      tipo: TipoInforme.TABLA,
      icono: 'Clock',
      fuente: { coleccion: 'pedidos' },
      campos: [
        { campo: 'codigo', etiqueta: 'Número', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'fecha', etiqueta: 'Fecha', tipo: TipoCampo.FECHA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 2 },
        { campo: 'clienteNombre', etiqueta: 'Cliente', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 3 },
        { campo: 'totales.totalPedido', etiqueta: 'Total', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 4 },
        { campo: 'estado', etiqueta: 'Estado', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 5 },
        { campo: 'prioridad', etiqueta: 'Prioridad', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 6 },
        { campo: 'fechaEntregaComprometida', etiqueta: 'Entrega', tipo: TipoCampo.FECHA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 7 },
      ],
      filtros: [
        { campo: 'estado', operador: OperadorFiltro.EN, valor: ['confirmado', 'en_proceso', 'parcialmente_servido'] },
      ],
      parametros: [],
      agrupaciones: [],
      ordenamiento: [{ campo: 'fechaEntregaComprometida', direccion: 'asc' }],
      config: { paginacion: true, mostrarTotales: true, exportable: true, formatos: ['excel', 'pdf'] },
      esPlantilla: true,
      compartido: true,
      orden: 2,
    },

    // ============================================
    // ALBARANES
    // ============================================
    {
      nombre: 'Listado de Albaranes',
      descripcion: 'Listado completo de albaranes de venta',
      modulo: ModuloInforme.ALBARANES,
      tipo: TipoInforme.TABLA,
      icono: 'Truck',
      fuente: { coleccion: 'albaranes' },
      campos: [
        { campo: 'codigo', etiqueta: 'Número', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'fecha', etiqueta: 'Fecha', tipo: TipoCampo.FECHA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 2 },
        { campo: 'clienteNombre', etiqueta: 'Cliente', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 3 },
        { campo: 'totales.totalAlbaran', etiqueta: 'Total', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 4 },
        { campo: 'estado', etiqueta: 'Estado', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 5 },
        { campo: 'facturado', etiqueta: 'Facturado', tipo: TipoCampo.BOOLEANO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 6 },
      ],
      filtros: [],
      parametros: [
        { nombre: 'fechaDesde', etiqueta: 'Desde', tipo: 'fecha', requerido: false },
        { nombre: 'fechaHasta', etiqueta: 'Hasta', tipo: 'fecha', requerido: false },
      ],
      agrupaciones: [],
      ordenamiento: [{ campo: 'fecha', direccion: 'desc' }],
      config: { paginacion: true, mostrarTotales: true, exportable: true, formatos: ['excel', 'pdf'] },
      esPlantilla: true,
      compartido: true,
      orden: 1,
    },
    {
      nombre: 'Albaranes Pendientes de Facturar',
      descripcion: 'Albaranes no facturados',
      modulo: ModuloInforme.ALBARANES,
      tipo: TipoInforme.TABLA,
      icono: 'AlertTriangle',
      fuente: { coleccion: 'albaranes' },
      campos: [
        { campo: 'codigo', etiqueta: 'Número', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'fecha', etiqueta: 'Fecha', tipo: TipoCampo.FECHA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 2 },
        { campo: 'clienteNombre', etiqueta: 'Cliente', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 3 },
        { campo: 'totales.totalAlbaran', etiqueta: 'Total', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 4 },
        { campo: 'estado', etiqueta: 'Estado', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 5 },
      ],
      filtros: [
        { campo: 'facturado', operador: OperadorFiltro.IGUAL, valor: false },
        { campo: 'estado', operador: OperadorFiltro.IGUAL, valor: 'entregado' },
      ],
      parametros: [],
      agrupaciones: [],
      ordenamiento: [{ campo: 'fecha', direccion: 'asc' }],
      config: { paginacion: true, mostrarTotales: true, exportable: true, formatos: ['excel', 'pdf'] },
      esPlantilla: true,
      compartido: true,
      orden: 2,
    },

    // ============================================
    // PROYECTOS
    // ============================================
    {
      nombre: 'Listado de Proyectos',
      descripcion: 'Listado completo de proyectos',
      modulo: ModuloInforme.PROYECTOS,
      tipo: TipoInforme.TABLA,
      icono: 'FolderKanban',
      fuente: { coleccion: 'proyectos' },
      campos: [
        { campo: 'codigo', etiqueta: 'Código', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'nombre', etiqueta: 'Nombre', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 2 },
        { campo: 'tipo', etiqueta: 'Tipo', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 3 },
        { campo: 'fechaInicio', etiqueta: 'Inicio', tipo: TipoCampo.FECHA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 4 },
        { campo: 'fechaFinPrevista', etiqueta: 'Fin Previsto', tipo: TipoCampo.FECHA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 5 },
        { campo: 'presupuestoAprobado', etiqueta: 'Presupuesto', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 6 },
        { campo: 'costeReal', etiqueta: 'Coste Real', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 7 },
        { campo: 'estado', etiqueta: 'Estado', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 8 },
        { campo: 'prioridad', etiqueta: 'Prioridad', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 9 },
      ],
      filtros: [],
      parametros: [],
      agrupaciones: [],
      ordenamiento: [{ campo: 'fechaInicio', direccion: 'desc' }],
      config: { paginacion: true, mostrarTotales: true, exportable: true, formatos: ['excel', 'pdf'] },
      esPlantilla: true,
      compartido: true,
      orden: 1,
    },

    // ============================================
    // PERSONAL
    // ============================================
    {
      nombre: 'Listado de Personal',
      descripcion: 'Listado completo del personal activo',
      modulo: ModuloInforme.PERSONAL,
      tipo: TipoInforme.TABLA,
      icono: 'Users',
      fuente: { coleccion: 'personal' },
      campos: [
        { campo: 'codigo', etiqueta: 'Código', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'nombre', etiqueta: 'Nombre', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 2 },
        { campo: 'apellidos', etiqueta: 'Apellidos', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 3 },
        { campo: 'contacto.emailCorporativo', etiqueta: 'Email', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 4 },
        { campo: 'contacto.telefonoMovil', etiqueta: 'Teléfono', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 5 },
        { campo: 'datosLaborales.puesto', etiqueta: 'Puesto', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 6 },
        { campo: 'datosLaborales.tipoContrato', etiqueta: 'Contrato', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 7 },
        { campo: 'estado', etiqueta: 'Estado', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 8 },
      ],
      filtros: [
        { campo: 'activo', operador: OperadorFiltro.IGUAL, valor: true },
      ],
      parametros: [],
      agrupaciones: [],
      ordenamiento: [{ campo: 'apellidos', direccion: 'asc' }],
      config: { paginacion: true, mostrarTotales: false, exportable: true, formatos: ['excel', 'pdf', 'csv'] },
      esPlantilla: true,
      compartido: true,
      orden: 1,
    },
    {
      nombre: 'Control de Fichajes',
      descripcion: 'Registro de fichajes de entrada y salida',
      modulo: ModuloInforme.PERSONAL,
      tipo: TipoInforme.TABLA,
      icono: 'Fingerprint',
      fuente: { coleccion: 'fichajes' },
      campos: [
        { campo: 'fecha', etiqueta: 'Fecha', tipo: TipoCampo.FECHA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'personalCodigo', etiqueta: 'Código', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 2 },
        { campo: 'personalNombre', etiqueta: 'Empleado', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 3 },
        { campo: 'departamentoNombre', etiqueta: 'Departamento', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 4 },
        { campo: 'horaEntrada', etiqueta: 'Entrada', tipo: TipoCampo.FECHA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 5 },
        { campo: 'horaSalida', etiqueta: 'Salida', tipo: TipoCampo.FECHA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 6 },
        { campo: 'horasTrabajadas', etiqueta: 'Horas', tipo: TipoCampo.NUMERO, visible: true, agregacion: TipoAgregacion.SUMA, orden: 7 },
        { campo: 'tipo', etiqueta: 'Tipo', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 8 },
        { campo: 'estado', etiqueta: 'Estado', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 9 },
      ],
      filtros: [],
      parametros: [
        { nombre: 'fechaDesde', etiqueta: 'Desde', tipo: 'fecha', requerido: true },
        { nombre: 'fechaHasta', etiqueta: 'Hasta', tipo: 'fecha', requerido: true },
      ],
      agrupaciones: [],
      ordenamiento: [{ campo: 'fecha', direccion: 'desc' }],
      config: { paginacion: true, mostrarTotales: true, exportable: true, formatos: ['excel', 'pdf'] },
      esPlantilla: true,
      compartido: true,
      orden: 2,
    },

    // ============================================
    // GENERAL (Informes fiscales)
    // ============================================
    {
      nombre: 'Libro de Facturas Emitidas',
      descripcion: 'Libro registro de facturas emitidas para IVA',
      modulo: ModuloInforme.GENERAL,
      tipo: TipoInforme.TABLA,
      icono: 'Book',
      fuente: { coleccion: 'facturas' },
      campos: [
        { campo: 'codigo', etiqueta: 'Nº Factura', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'fecha', etiqueta: 'Fecha', tipo: TipoCampo.FECHA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 2 },
        { campo: 'clienteNif', etiqueta: 'NIF', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 3 },
        { campo: 'clienteNombre', etiqueta: 'Cliente', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 4 },
        { campo: 'totales.subtotalNeto', etiqueta: 'Base', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 5 },
        { campo: 'totales.totalIva', etiqueta: 'Cuota IVA', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 6 },
        { campo: 'totales.totalFactura', etiqueta: 'Total', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 7 },
      ],
      filtros: [],
      parametros: [
        { nombre: 'fechaDesde', etiqueta: 'Desde', tipo: 'fecha', requerido: true },
        { nombre: 'fechaHasta', etiqueta: 'Hasta', tipo: 'fecha', requerido: true },
      ],
      agrupaciones: [],
      ordenamiento: [{ campo: 'fecha', direccion: 'asc' }],
      config: { paginacion: true, mostrarTotales: true, exportable: true, formatos: ['excel', 'pdf', 'csv'] },
      esPlantilla: true,
      compartido: true,
      orden: 1,
    },
    {
      nombre: 'Libro de Facturas Recibidas',
      descripcion: 'Libro registro de facturas recibidas (compras) para IVA',
      modulo: ModuloInforme.GENERAL,
      tipo: TipoInforme.TABLA,
      icono: 'Book',
      fuente: { coleccion: 'facturacompras' },
      campos: [
        { campo: 'numeroFacturaProveedor', etiqueta: 'Nº Factura', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'fecha', etiqueta: 'Fecha', tipo: TipoCampo.FECHA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 2 },
        { campo: 'proveedorNif', etiqueta: 'NIF', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 3 },
        { campo: 'proveedorNombre', etiqueta: 'Proveedor', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 4 },
        { campo: 'totales.subtotalNeto', etiqueta: 'Base', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 5 },
        { campo: 'totales.totalIva', etiqueta: 'Cuota IVA', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 6 },
        { campo: 'totales.totalFactura', etiqueta: 'Total', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 7 },
      ],
      filtros: [],
      parametros: [
        { nombre: 'fechaDesde', etiqueta: 'Desde', tipo: 'fecha', requerido: true },
        { nombre: 'fechaHasta', etiqueta: 'Hasta', tipo: 'fecha', requerido: true },
      ],
      agrupaciones: [],
      ordenamiento: [{ campo: 'fecha', direccion: 'asc' }],
      config: { paginacion: true, mostrarTotales: true, exportable: true, formatos: ['excel', 'pdf', 'csv'] },
      esPlantilla: true,
      compartido: true,
      orden: 2,
    },
    {
      nombre: 'Resumen IVA Repercutido',
      descripcion: 'Resumen de IVA en ventas por tipo impositivo',
      modulo: ModuloInforme.GENERAL,
      tipo: TipoInforme.TABLA,
      icono: 'Calculator',
      fuente: { coleccion: 'facturas' },
      campos: [
        { campo: 'codigo', etiqueta: 'Nº Factura', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'fecha', etiqueta: 'Fecha', tipo: TipoCampo.FECHA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 2 },
        { campo: 'clienteNif', etiqueta: 'NIF', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 3 },
        { campo: 'clienteNombre', etiqueta: 'Cliente', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 4 },
        { campo: 'totales.subtotalBruto', etiqueta: 'Importe Bruto', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 5 },
        { campo: 'totales.totalDescuentos', etiqueta: 'Descuentos', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 6 },
        { campo: 'totales.subtotalNeto', etiqueta: 'Base Imponible', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 7 },
        { campo: 'totales.totalIva', etiqueta: 'Cuota IVA', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 8 },
        { campo: 'totales.totalRecargoEquivalencia', etiqueta: 'Recargo Eq.', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 9 },
        { campo: 'totales.totalFactura', etiqueta: 'Total Factura', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 10 },
      ],
      filtros: [],
      parametros: [
        { nombre: 'fechaDesde', etiqueta: 'Desde', tipo: 'fecha', requerido: true },
        { nombre: 'fechaHasta', etiqueta: 'Hasta', tipo: 'fecha', requerido: true },
      ],
      agrupaciones: [],
      ordenamiento: [{ campo: 'fecha', direccion: 'asc' }],
      config: { paginacion: true, mostrarTotales: true, exportable: true, formatos: ['excel', 'pdf', 'csv'] },
      esPlantilla: true,
      compartido: true,
      orden: 3,
    },
    {
      nombre: 'Resumen IVA Soportado',
      descripcion: 'Resumen de IVA en compras por tipo impositivo',
      modulo: ModuloInforme.GENERAL,
      tipo: TipoInforme.TABLA,
      icono: 'Calculator',
      fuente: { coleccion: 'facturacompras' },
      campos: [
        { campo: 'numeroFacturaProveedor', etiqueta: 'Nº Factura', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'fecha', etiqueta: 'Fecha', tipo: TipoCampo.FECHA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 2 },
        { campo: 'proveedorNif', etiqueta: 'NIF', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 3 },
        { campo: 'proveedorNombre', etiqueta: 'Proveedor', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 4 },
        { campo: 'totales.subtotalBruto', etiqueta: 'Importe Bruto', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 5 },
        { campo: 'totales.totalDescuentos', etiqueta: 'Descuentos', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 6 },
        { campo: 'totales.subtotalNeto', etiqueta: 'Base Imponible', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 7 },
        { campo: 'totales.totalIva', etiqueta: 'Cuota IVA', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 8 },
        { campo: 'totales.totalFactura', etiqueta: 'Total Factura', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 9 },
      ],
      filtros: [],
      parametros: [
        { nombre: 'fechaDesde', etiqueta: 'Desde', tipo: 'fecha', requerido: true },
        { nombre: 'fechaHasta', etiqueta: 'Hasta', tipo: 'fecha', requerido: true },
      ],
      agrupaciones: [],
      ordenamiento: [{ campo: 'fecha', direccion: 'asc' }],
      config: { paginacion: true, mostrarTotales: true, exportable: true, formatos: ['excel', 'pdf', 'csv'] },
      esPlantilla: true,
      compartido: true,
      orden: 4,
    },

    // ============================================
    // ANÁLISIS ABC DE PRODUCTOS (STOCK)
    // ============================================
    {
      nombre: 'Análisis ABC de Productos por Ventas',
      descripcion: 'Clasificación ABC de productos según ingresos por ventas (Pareto 80/20)',
      modulo: ModuloInforme.STOCK,
      tipo: TipoInforme.MIXTO,
      icono: 'BarChart3',
      fuente: { coleccion: 'productos' },
      campos: [
        { campo: 'sku', etiqueta: 'SKU', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'nombre', etiqueta: 'Producto', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 2 },
        { campo: 'familia', etiqueta: 'Familia', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 3 },
        { campo: 'estadisticas.ingresoTotal', etiqueta: 'Ingresos', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 4 },
        { campo: 'estadisticas.vecesVendido', etiqueta: 'Uds. Vendidas', tipo: TipoCampo.NUMERO, visible: true, agregacion: TipoAgregacion.SUMA, orden: 5 },
        { campo: 'estadisticas.margenTotal', etiqueta: 'Margen', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 6 },
      ],
      filtros: [
        { campo: 'activo', operador: OperadorFiltro.IGUAL, valor: true },
        { campo: 'estadisticas.ingresoTotal', operador: OperadorFiltro.MAYOR, valor: 0 },
      ],
      parametros: [],
      agrupaciones: [],
      ordenamiento: [{ campo: 'estadisticas.ingresoTotal', direccion: 'desc' }],
      grafico: {
        tipo: TipoGraficoInforme.BARRA,
        ejeX: 'nombre',
        series: [{ campo: 'estadisticas.ingresoTotal', etiqueta: 'Ingresos', color: '#3b82f6' }],
      },
      config: { paginacion: true, mostrarTotales: true, exportable: true, formatos: ['excel', 'pdf'] },
      esPlantilla: true,
      compartido: true,
      orden: 4,
    },
    {
      nombre: 'Análisis ABC de Productos por Margen',
      descripcion: 'Clasificación ABC de productos según margen de beneficio',
      modulo: ModuloInforme.STOCK,
      tipo: TipoInforme.MIXTO,
      icono: 'TrendingUp',
      fuente: { coleccion: 'productos' },
      campos: [
        { campo: 'sku', etiqueta: 'SKU', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'nombre', etiqueta: 'Producto', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 2 },
        { campo: 'familia', etiqueta: 'Familia', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 3 },
        { campo: 'estadisticas.margenTotal', etiqueta: 'Margen Total', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 4 },
        { campo: 'estadisticas.ingresoTotal', etiqueta: 'Ingresos', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 5 },
        { campo: 'estadisticas.vecesVendido', etiqueta: 'Uds. Vendidas', tipo: TipoCampo.NUMERO, visible: true, agregacion: TipoAgregacion.SUMA, orden: 6 },
      ],
      filtros: [
        { campo: 'activo', operador: OperadorFiltro.IGUAL, valor: true },
        { campo: 'estadisticas.margenTotal', operador: OperadorFiltro.MAYOR, valor: 0 },
      ],
      parametros: [],
      agrupaciones: [],
      ordenamiento: [{ campo: 'estadisticas.margenTotal', direccion: 'desc' }],
      grafico: {
        tipo: TipoGraficoInforme.BARRA,
        ejeX: 'nombre',
        series: [{ campo: 'estadisticas.margenTotal', etiqueta: 'Margen', color: '#10b981' }],
      },
      config: { paginacion: true, mostrarTotales: true, exportable: true, formatos: ['excel', 'pdf'] },
      esPlantilla: true,
      compartido: true,
      orden: 5,
    },
    {
      nombre: 'Rotación de Inventario',
      descripcion: 'Análisis de rotación de productos en el almacén',
      modulo: ModuloInforme.STOCK,
      tipo: TipoInforme.TABLA,
      icono: 'RefreshCw',
      fuente: { coleccion: 'productos' },
      campos: [
        { campo: 'sku', etiqueta: 'SKU', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'nombre', etiqueta: 'Producto', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 2 },
        { campo: 'stock.cantidad', etiqueta: 'Stock Actual', tipo: TipoCampo.NUMERO, visible: true, agregacion: TipoAgregacion.SUMA, orden: 3 },
        { campo: 'estadisticas.vecesVendido', etiqueta: 'Vendidos (año)', tipo: TipoCampo.NUMERO, visible: true, agregacion: TipoAgregacion.SUMA, orden: 4 },
        { campo: 'precios.compra', etiqueta: 'P. Coste', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 5 },
        { campo: 'estadisticas.ultimaVenta', etiqueta: 'Última Venta', tipo: TipoCampo.FECHA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 6 },
        { campo: 'estadisticas.ultimaCompra', etiqueta: 'Última Compra', tipo: TipoCampo.FECHA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 7 },
      ],
      filtros: [
        { campo: 'activo', operador: OperadorFiltro.IGUAL, valor: true },
        { campo: 'stock.cantidad', operador: OperadorFiltro.MAYOR, valor: 0 },
      ],
      parametros: [],
      agrupaciones: [],
      ordenamiento: [{ campo: 'estadisticas.vecesVendido', direccion: 'desc' }],
      config: { paginacion: true, mostrarTotales: true, exportable: true, formatos: ['excel', 'pdf'] },
      esPlantilla: true,
      compartido: true,
      orden: 6,
    },
    {
      nombre: 'Valoración de Stock',
      descripcion: 'Valor del inventario a precio de coste y venta',
      modulo: ModuloInforme.STOCK,
      tipo: TipoInforme.TABLA,
      icono: 'DollarSign',
      fuente: { coleccion: 'productos' },
      campos: [
        { campo: 'sku', etiqueta: 'SKU', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'nombre', etiqueta: 'Producto', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 2 },
        { campo: 'familia', etiqueta: 'Familia', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 3 },
        { campo: 'stock.cantidad', etiqueta: 'Stock', tipo: TipoCampo.NUMERO, visible: true, agregacion: TipoAgregacion.SUMA, orden: 4 },
        { campo: 'precios.compra', etiqueta: 'P. Coste', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 5 },
        { campo: 'precios.venta', etiqueta: 'P. Venta', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 6 },
      ],
      filtros: [
        { campo: 'activo', operador: OperadorFiltro.IGUAL, valor: true },
        { campo: 'stock.cantidad', operador: OperadorFiltro.MAYOR, valor: 0 },
      ],
      parametros: [],
      agrupaciones: [],
      ordenamiento: [{ campo: 'familia', direccion: 'asc' }, { campo: 'nombre', direccion: 'asc' }],
      config: { paginacion: true, mostrarTotales: true, exportable: true, formatos: ['excel', 'pdf'] },
      esPlantilla: true,
      compartido: true,
      orden: 7,
    },

    // ============================================
    // CRM
    // ============================================
    {
      nombre: 'Pipeline de Oportunidades',
      descripcion: 'Oportunidades comerciales por etapa del pipeline',
      modulo: ModuloInforme.CRM,
      tipo: TipoInforme.MIXTO,
      icono: 'Target',
      fuente: { coleccion: 'oportunidades' },
      campos: [
        { campo: 'codigo', etiqueta: 'Código', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'titulo', etiqueta: 'Oportunidad', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 2 },
        { campo: 'clienteNombre', etiqueta: 'Cliente', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 3 },
        { campo: 'etapa', etiqueta: 'Etapa', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 4 },
        { campo: 'valorEstimado', etiqueta: 'Valor', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 5 },
        { campo: 'probabilidad', etiqueta: 'Prob. %', tipo: TipoCampo.PORCENTAJE, visible: true, agregacion: TipoAgregacion.PROMEDIO, orden: 6 },
        { campo: 'fechaCierreEstimada', etiqueta: 'Cierre Est.', tipo: TipoCampo.FECHA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 7 },
        { campo: 'comercialNombre', etiqueta: 'Comercial', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 8 },
      ],
      filtros: [
        { campo: 'estado', operador: OperadorFiltro.IGUAL, valor: 'abierta' },
      ],
      parametros: [],
      agrupaciones: [{ campo: 'etapa', orden: 'asc' }],
      ordenamiento: [{ campo: 'valorEstimado', direccion: 'desc' }],
      grafico: {
        tipo: TipoGraficoInforme.BARRA,
        ejeX: 'etapa',
        series: [{ campo: 'valorEstimado', etiqueta: 'Valor', color: '#8b5cf6' }],
      },
      config: { paginacion: true, mostrarTotales: true, exportable: true, formatos: ['excel', 'pdf'] },
      esPlantilla: true,
      compartido: true,
      orden: 1,
    },
    {
      nombre: 'Actividades Comerciales',
      descripcion: 'Registro de actividades comerciales realizadas',
      modulo: ModuloInforme.CRM,
      tipo: TipoInforme.TABLA,
      icono: 'Activity',
      fuente: { coleccion: 'actividades' },
      campos: [
        { campo: 'fecha', etiqueta: 'Fecha', tipo: TipoCampo.FECHA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'tipo', etiqueta: 'Tipo', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 2 },
        { campo: 'asunto', etiqueta: 'Asunto', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 3 },
        { campo: 'clienteNombre', etiqueta: 'Cliente', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 4 },
        { campo: 'usuarioNombre', etiqueta: 'Responsable', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 5 },
        { campo: 'duracion', etiqueta: 'Duración (min)', tipo: TipoCampo.NUMERO, visible: true, agregacion: TipoAgregacion.SUMA, orden: 6 },
        { campo: 'estado', etiqueta: 'Estado', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 7 },
      ],
      filtros: [],
      parametros: [
        { nombre: 'fechaDesde', etiqueta: 'Desde', tipo: 'fecha', requerido: false },
        { nombre: 'fechaHasta', etiqueta: 'Hasta', tipo: 'fecha', requerido: false },
      ],
      agrupaciones: [],
      ordenamiento: [{ campo: 'fecha', direccion: 'desc' }],
      config: { paginacion: true, mostrarTotales: true, exportable: true, formatos: ['excel', 'pdf'] },
      esPlantilla: true,
      compartido: true,
      orden: 2,
    },
    {
      nombre: 'Rendimiento Comercial',
      descripcion: 'Análisis de rendimiento de comerciales',
      modulo: ModuloInforme.CRM,
      tipo: TipoInforme.MIXTO,
      icono: 'UserCheck',
      fuente: { coleccion: 'oportunidades' },
      campos: [
        { campo: 'comercialNombre', etiqueta: 'Comercial', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'valorEstimado', etiqueta: 'Valor Total', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 2 },
        { campo: '_id', etiqueta: 'Nº Oportunidades', tipo: TipoCampo.NUMERO, visible: true, agregacion: TipoAgregacion.CONTEO, orden: 3 },
        { campo: 'probabilidad', etiqueta: 'Prob. Media', tipo: TipoCampo.PORCENTAJE, visible: true, agregacion: TipoAgregacion.PROMEDIO, orden: 4 },
      ],
      filtros: [
        { campo: 'estado', operador: OperadorFiltro.IGUAL, valor: 'abierta' },
      ],
      parametros: [],
      agrupaciones: [{ campo: 'comercialNombre', orden: 'asc' }],
      ordenamiento: [{ campo: 'valorEstimado', direccion: 'desc' }],
      grafico: {
        tipo: TipoGraficoInforme.BARRA_HORIZONTAL,
        ejeX: 'comercialNombre',
        series: [{ campo: 'valorEstimado', etiqueta: 'Valor', color: '#f97316' }],
      },
      config: { paginacion: false, mostrarTotales: true, exportable: true, formatos: ['excel', 'pdf'] },
      esPlantilla: true,
      compartido: true,
      orden: 3,
    },

    // ============================================
    // TPV
    // ============================================
    {
      nombre: 'Ventas por TPV',
      descripcion: 'Resumen de ventas por punto de venta',
      modulo: ModuloInforme.TPV,
      tipo: TipoInforme.MIXTO,
      icono: 'Monitor',
      fuente: { coleccion: 'ventas' },
      campos: [
        { campo: 'tpvNombre', etiqueta: 'TPV', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'totales.total', etiqueta: 'Total Ventas', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 2 },
        { campo: '_id', etiqueta: 'Nº Tickets', tipo: TipoCampo.NUMERO, visible: true, agregacion: TipoAgregacion.CONTEO, orden: 3 },
        { campo: 'totales.totalIva', etiqueta: 'IVA', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 4 },
      ],
      filtros: [],
      parametros: [
        { nombre: 'fechaDesde', etiqueta: 'Desde', tipo: 'fecha', requerido: true },
        { nombre: 'fechaHasta', etiqueta: 'Hasta', tipo: 'fecha', requerido: true },
      ],
      agrupaciones: [{ campo: 'tpvNombre', orden: 'asc' }],
      ordenamiento: [{ campo: 'totales.total', direccion: 'desc' }],
      grafico: {
        tipo: TipoGraficoInforme.CIRCULAR,
        ejeX: 'tpvNombre',
        series: [{ campo: 'totales.total', etiqueta: 'Ventas', color: '#3b82f6' }],
      },
      config: { paginacion: false, mostrarTotales: true, exportable: true, formatos: ['excel', 'pdf'] },
      esPlantilla: true,
      compartido: true,
      orden: 1,
    },
    {
      nombre: 'Ventas por Forma de Pago',
      descripcion: 'Desglose de ventas según método de pago',
      modulo: ModuloInforme.TPV,
      tipo: TipoInforme.MIXTO,
      icono: 'CreditCard',
      fuente: { coleccion: 'ventas' },
      campos: [
        { campo: 'formaPagoNombre', etiqueta: 'Forma de Pago', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'totales.total', etiqueta: 'Importe', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 2 },
        { campo: '_id', etiqueta: 'Nº Operaciones', tipo: TipoCampo.NUMERO, visible: true, agregacion: TipoAgregacion.CONTEO, orden: 3 },
      ],
      filtros: [],
      parametros: [
        { nombre: 'fechaDesde', etiqueta: 'Desde', tipo: 'fecha', requerido: true },
        { nombre: 'fechaHasta', etiqueta: 'Hasta', tipo: 'fecha', requerido: true },
      ],
      agrupaciones: [{ campo: 'formaPagoNombre', orden: 'asc' }],
      ordenamiento: [{ campo: 'totales.total', direccion: 'desc' }],
      grafico: {
        tipo: TipoGraficoInforme.DONA,
        ejeX: 'formaPagoNombre',
        series: [{ campo: 'totales.total', etiqueta: 'Importe', color: '#10b981' }],
      },
      config: { paginacion: false, mostrarTotales: true, exportable: true, formatos: ['excel', 'pdf'] },
      esPlantilla: true,
      compartido: true,
      orden: 2,
    },
    {
      nombre: 'Cierre de Caja',
      descripcion: 'Resumen de cierres de caja por día',
      modulo: ModuloInforme.TPV,
      tipo: TipoInforme.TABLA,
      icono: 'Calculator',
      fuente: { coleccion: 'cajas' },
      campos: [
        { campo: 'fecha', etiqueta: 'Fecha', tipo: TipoCampo.FECHA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'tpvNombre', etiqueta: 'TPV', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 2 },
        { campo: 'usuarioNombre', etiqueta: 'Usuario', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 3 },
        { campo: 'efectivoInicial', etiqueta: 'Efectivo Inicial', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 4 },
        { campo: 'efectivoFinal', etiqueta: 'Efectivo Final', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 5 },
        { campo: 'totalVentas', etiqueta: 'Total Ventas', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 6 },
        { campo: 'diferencia', etiqueta: 'Diferencia', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 7 },
      ],
      filtros: [
        { campo: 'estado', operador: OperadorFiltro.IGUAL, valor: 'cerrada' },
      ],
      parametros: [
        { nombre: 'fechaDesde', etiqueta: 'Desde', tipo: 'fecha', requerido: true },
        { nombre: 'fechaHasta', etiqueta: 'Hasta', tipo: 'fecha', requerido: true },
      ],
      agrupaciones: [],
      ordenamiento: [{ campo: 'fecha', direccion: 'desc' }],
      config: { paginacion: true, mostrarTotales: true, exportable: true, formatos: ['excel', 'pdf'] },
      esPlantilla: true,
      compartido: true,
      orden: 3,
    },

    // ============================================
    // TESORERÍA
    // ============================================
    {
      nombre: 'Flujo de Caja',
      descripcion: 'Movimientos de tesorería con saldo acumulado',
      modulo: ModuloInforme.TESORERIA,
      tipo: TipoInforme.MIXTO,
      icono: 'ArrowUpDown',
      fuente: { coleccion: 'movimientosbancarios' },
      campos: [
        { campo: 'fecha', etiqueta: 'Fecha', tipo: TipoCampo.FECHA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'concepto', etiqueta: 'Concepto', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 2 },
        { campo: 'tipo', etiqueta: 'Tipo', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 3 },
        { campo: 'importe', etiqueta: 'Importe', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 4 },
        { campo: 'cuentaNombre', etiqueta: 'Cuenta', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 5 },
      ],
      filtros: [],
      parametros: [
        { nombre: 'fechaDesde', etiqueta: 'Desde', tipo: 'fecha', requerido: true },
        { nombre: 'fechaHasta', etiqueta: 'Hasta', tipo: 'fecha', requerido: true },
      ],
      agrupaciones: [],
      ordenamiento: [{ campo: 'fecha', direccion: 'desc' }],
      grafico: {
        tipo: TipoGraficoInforme.LINEA,
        ejeX: 'fecha',
        series: [{ campo: 'importe', etiqueta: 'Importe', color: '#3b82f6' }],
      },
      config: { paginacion: true, mostrarTotales: true, exportable: true, formatos: ['excel', 'pdf'] },
      esPlantilla: true,
      compartido: true,
      orden: 1,
    },
    {
      nombre: 'Previsión de Tesorería',
      descripcion: 'Vencimientos pendientes de cobro y pago',
      modulo: ModuloInforme.TESORERIA,
      tipo: TipoInforme.TABLA,
      icono: 'Calendar',
      fuente: { coleccion: 'vencimientos' },
      campos: [
        { campo: 'fechaVencimiento', etiqueta: 'Vencimiento', tipo: TipoCampo.FECHA, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 1 },
        { campo: 'tipo', etiqueta: 'Tipo', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 2 },
        { campo: 'documentoCodigo', etiqueta: 'Documento', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 3 },
        { campo: 'terceroNombre', etiqueta: 'Tercero', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 4 },
        { campo: 'importePendiente', etiqueta: 'Importe Pdte.', tipo: TipoCampo.MONEDA, visible: true, agregacion: TipoAgregacion.SUMA, orden: 5 },
        { campo: 'estado', etiqueta: 'Estado', tipo: TipoCampo.TEXTO, visible: true, agregacion: TipoAgregacion.NINGUNA, orden: 6 },
      ],
      filtros: [
        { campo: 'estado', operador: OperadorFiltro.IGUAL, valor: 'pendiente' },
      ],
      parametros: [
        { nombre: 'fechaDesde', etiqueta: 'Desde', tipo: 'fecha', requerido: false },
        { nombre: 'fechaHasta', etiqueta: 'Hasta', tipo: 'fecha', requerido: false },
      ],
      agrupaciones: [],
      ordenamiento: [{ campo: 'fechaVencimiento', direccion: 'asc' }],
      config: { paginacion: true, mostrarTotales: true, exportable: true, formatos: ['excel', 'pdf'] },
      esPlantilla: true,
      compartido: true,
      orden: 2,
    },
  ];
}

export default obtenerInformesPredefinidos;
